return {
  {'hrsh7th/nvim-cmp', lazy = true},
  {'neovim/nvim-lspconfig', lazy = true},
  {'hrsh7th/cmp-nvim-lsp', lazy = true},
  {'hrsh7th/cmp-buffer', lazy = true},
  {'hrsh7th/cmp-path', lazy = true},
  {'hrsh7th/cmp-cmdline', lazy = false},
  {'saadparwaiz1/cmp_luasnip', lazy = true},
  {'L3MON4D3/LuaSnip', lazy = true},
  {'jose-elias-alvarez/null-ls.nvim', lazy = true},
  {"glepnir/lspsaga.nvim", event = "LspAttach", dependencies = {{"nvim-tree/nvim-web-devicons"}, {"nvim-treesitter/nvim-treesitter"}}}, 
  {"folke/trouble.nvim", requires = "nvim-tree/nvim-web-devicons"},

  {"nvim-lua/plenary.nvim", lazy = true},
  {'akinsho/toggleterm.nvim', lazy = true},
  {'akinsho/bufferline.nvim', commit = "b337fd393cef2e3679689d220e2628722c20ddcb", dependencies = 'nvim-tree/nvim-web-devicons', lazy = true},
  {'nvim-telescope/telescope.nvim', branch = '0.1.x', dependencies = 'nvim-lua/plenary.nvim', lazy = true},
  {'CRAG666/code_runner.nvim', dependencies = 'nvim-lua/plenary.nvim', lazy = true},
  'goolord/alpha-nvim',
  'lewis6991/impatient.nvim',
  {'Civitasv/cmake-tools.nvim', lazy = true},
  {'lewis6991/gitsigns.nvim', lazy = true },
  'rcarriga/nvim-notify',
  {'dstein64/vim-startuptime', lazy = true},
  {'simrat39/symbols-outline.nvim', lazy = true},
  {"nvim-neo-tree/neo-tree.nvim", branch = "v2.x", dependencies = {"nvim-lua/plenary.nvim", "nvim-tree/nvim-web-devicons", "MunifTanjim/nui.nvim",}},
  'andweeb/presence.nvim',
  {'glepnir/galaxyline.nvim', branch = 'main', dependencies = { 'nvim-tree/nvim-web-devicons'}},
  {'windwp/nvim-autopairs', lazy = true},
  {"Shatur/neovim-session-manager", lazy = true},
  { "catppuccin/nvim", name = "catppuccin" },
  {'numToStr/Comment.nvim', lazy = true},
  'mrjones2014/smart-splits.nvim',
  {'famiu/bufdelete.nvim', lazy = true},
  {"nvim-telescope/telescope-project.nvim", lazy = true},
  {"p00f/nvim-ts-rainbow", lazy = true},
  {"nvim-treesitter/nvim-treesitter", build = ":TSUpdate", lazy = true},
  --Please make sure you install markdown and markdown_inline parser
}


