vim.keymap.set("n", "<S-h>", ":bprevious<CR>")
vim.keymap.set("n", "<S-l>", ":bnext<CR>")
vim.keymap.set("n", "b", ":Telescope buffers<CR>")
vim.keymap.set("n", "<ESC>", ":nohlsearch<Bar>:echo<CR>")

vim.keymap.set("n", "fd", ":lua require('bufdelete').bufdelete(0, true)<CR>")
vim.keymap.set("n", "<F1>", ":SymbolsOutline<CR>")
vim.keymap.set('n', '<C-h>', require('smart-splits').move_cursor_left)
vim.keymap.set('n', '<C-j>', require('smart-splits').move_cursor_down)
vim.keymap.set('n', '<C-k>', require('smart-splits').move_cursor_up)
vim.keymap.set('n', '<C-l>', require('smart-splits').move_cursor_right)
vim.keymap.set('n', '<C-Up>', require('smart-splits').resize_up)
vim.keymap.set('n', '<C-Down>', require('smart-splits').resize_down)
vim.keymap.set('n', '<C-Left>', require('smart-splits').resize_left)
vim.keymap.set('n', '<C-Right>', require('smart-splits').resize_right)
vim.keymap.set("n", "<leader>lg", "<cmd>lua _lazygit_toggle()<CR>")
vim.keymap.set("n", "<leader>g", "<cmd>lua _gdb_toggle()<CR>")
vim.keymap.set("n", "f", ":Neotree<CR>")
vim.keymap.set("n", "<C-g>", ":Neotree git_status<CR>")
vim.keymap.set("n", "qa", ":qa!<CR>")
